//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fresh_and_FIt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<long> TransactionId { get; set; }
        public string Status { get; set; }
        public System.DateTime OrderDate { get; set; }
    }
}
